[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#00c73c"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1e222b"
textColor = "#fafafa"
font = "sans serif"
